# Site settings
title: NUSMods Blog
email: nusmods@googlegroups.com
description: At NUSMods, we build cool stuff. Here's where we write about them.
url: https://blog.nusmods.com # the base hostname & protocol for your site
facebook_username: nusmods
twitter_username: nusmods
github_username:  nusmodifications

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 5
encoding: UTF-8
